version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: froome-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: froome
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=password" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - froome-network

  eureka-service:
    image: eureka-service
    depends_on:
      config-service:
        condition: service_healthy
    build:
      context: .
      dockerfile: eureka-service/Dockerfile
    environment:
      PORT: 8986
    ports:
      - "8986:8986"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:8986/actuator/health | grep UP" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - froome-network

  gateway-service:
    image: gateway-service
    depends_on:
      eureka-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    ports:
      - "8987:8987"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:8987/actuator/health | grep UP" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - froome-network

  config-service:
    image: config-service
    build:
      context: .
      dockerfile: config-service/Dockerfile
    environment:
      GIT_URI: https://github.com/IzaakAM/AOS.git
      PORT: 8985
    ports:
      - "8985:8985"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:8985/actuator/health | grep UP" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - froome-network

  user:
    image: user-service
    depends_on:
      db:
        condition: service_healthy
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      DB_URL: jdbc:mysql://froome-db:3306/froome
      SPRING_CLOUD_CONFIG_URI: http://config-service:8985
      SPRING_PROFILES_ACTIVE: docker
      PORT: 8980
    ports:
      - "8980:8980"
    networks:
      - froome-network

  product:
    image: product-service
    depends_on:
      db:
        condition: service_healthy
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    build:
      context: .
      dockerfile: product-service/Dockerfile
    environment:
      DB_URL: jdbc:mysql://froome-db:3306/froome
      SPRING_CLOUD_CONFIG_URI: http://config-service:8985
      SPRING_PROFILES_ACTIVE: docker
      PORT: 8981
    ports:
      - "8981:8981"
    networks:
      - froome-network

  payment:
    image: payment-service
    depends_on:
      db:
        condition: service_healthy
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    environment:
      DB_URL: jdbc:mysql://froome-db:3306/froome
      SPRING_CLOUD_CONFIG_URI: http://config-service:8985
      SPRING_PROFILES_ACTIVE: docker
      PORT: 8982
    ports:
      - "8982:8982"
    networks:
      - froome-network

  order:
    image: order-service
    depends_on:
      db:
        condition: service_healthy
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    build:
      context: .
      dockerfile: order-service/Dockerfile
    environment:
      DB_URL: jdbc:mysql://froome-db:3306/froome
      SPRING_CLOUD_CONFIG_URI: http://config-service:8985
      SPRING_PROFILES_ACTIVE: docker
      PORT: 8983
    ports:
      - "8983:8983"
    networks:
      - froome-network

  vue-app:
    image: froome-ui
    build:
      context: ./froome-ui
      dockerfile: Dockerfile
    depends_on:
      - user
      - product
      - payment
      - order
      - eureka-service
    ports:
      - "8984:8984"
    networks:
      - froome-network

networks:
  froome-network:

volumes:
  db_data:
