server:
  port: ${PORT:8986}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-service:8986/eureka/

spring:
  application:
    name: eureka-service


logging:
  level:
    root: info