server:
  port: ${PORT:8985}

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI:https://github.com/IzaakAM/AOS.git}
          search-paths: 'config-service'
          default-label: main

logging:
  level:
    #org.springframework.cloud.config.client: INFO
    #org.springframework.cloud.context.scope.GenericScope: INFO
    #org.springframework.boot.context.config: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8986/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


